trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'D:\a\1\s\Spectabis-WPF\bin\Release\'
    includeRootFolder: false
    archiveType: '7z'
    sevenZipCompression: 'normal'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).7z'
    replaceExistingArchive: true
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'Spectabis-WPF'
    publishLocation: 'pipeline'